[bundle]
outdir = "dist"
minify = true
sourcemap = true
target = "browser"
format = "esm"
naming = "[dir]/[name].min.[ext]"

[bundle.minifyOptions]
html = true
css = true
js = true
whitespace = true
syntax = true 